//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class Education : NonProductiveTask
    {
        #region Primitive Properties
    
        public virtual System.DateTimeOffset StartOffset
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Task Task
        {
            get { return _task; }
            set
            {
                if (!ReferenceEquals(_task, value))
                {
                    var previousValue = _task;
                    _task = value;
                    FixupTask(previousValue);
                }
            }
        }
        private Task _task;
    
        public virtual ICollection<EducatingOperator> EducatingOperators
        {
            get
            {
                if (_educatingOperators == null)
                {
                    var newCollection = new FixupCollection<EducatingOperator>();
                    newCollection.CollectionChanged += FixupEducatingOperators;
                    _educatingOperators = newCollection;
                }
                return _educatingOperators;
            }
            set
            {
                if (!ReferenceEquals(_educatingOperators, value))
                {
                    var previousValue = _educatingOperators as FixupCollection<EducatingOperator>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEducatingOperators;
                    }
                    _educatingOperators = value;
                    var newValue = value as FixupCollection<EducatingOperator>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEducatingOperators;
                    }
                }
            }
        }
        private ICollection<EducatingOperator> _educatingOperators;

        #endregion

        #region Association Fixup
    
        private void FixupTask(Task previousValue)
        {
            if (previousValue != null && previousValue.Educations.Contains(this))
            {
                previousValue.Educations.Remove(this);
            }
    
            if (Task != null)
            {
                if (!Task.Educations.Contains(this))
                {
                    Task.Educations.Add(this);
                }
            }
        }
    
        private void FixupEducatingOperators(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (EducatingOperator item in e.NewItems)
                {
                    item.Education = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (EducatingOperator item in e.OldItems)
                {
                    if (ReferenceEquals(item.Education, this))
                    {
                        item.Education = null;
                    }
                }
            }
        }

        #endregion

    }
}
