//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class Holiday
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual System.DateTime Date
        {
            get;
            set;
        }
    
        public virtual byte BusinessStateNr
        {
            get { return _businessStateNr; }
            set { _businessStateNr = value; }
        }
        private byte _businessStateNr = 0;
    
        public virtual bool IsRecurrent
        {
            get { return _isRecurrent; }
            set { _isRecurrent = value; }
        }
        private bool _isRecurrent = true;

        #endregion

    }
}
