//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class SpecialSkill
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Reserve1
        {
            get;
            set;
        }
    
        public virtual string Reserve2
        {
            get;
            set;
        }
    
        public virtual string Reserve3
        {
            get;
            set;
        }
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<OperatorActivity> OperatorActivities
        {
            get
            {
                if (_operatorActivities == null)
                {
                    var newCollection = new FixupCollection<OperatorActivity>();
                    newCollection.CollectionChanged += FixupOperatorActivities;
                    _operatorActivities = newCollection;
                }
                return _operatorActivities;
            }
            set
            {
                if (!ReferenceEquals(_operatorActivities, value))
                {
                    var previousValue = _operatorActivities as FixupCollection<OperatorActivity>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupOperatorActivities;
                    }
                    _operatorActivities = value;
                    var newValue = value as FixupCollection<OperatorActivity>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupOperatorActivities;
                    }
                }
            }
        }
        private ICollection<OperatorActivity> _operatorActivities;

        #endregion

        #region Association Fixup
    
        private void FixupOperatorActivities(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (OperatorActivity item in e.NewItems)
                {
                    item.SpecialSkill = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (OperatorActivity item in e.OldItems)
                {
                    if (ReferenceEquals(item.SpecialSkill, this))
                    {
                        item.SpecialSkill = null;
                    }
                }
            }
        }

        #endregion

    }
}
