//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class TaskReport
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual byte Status
        {
            get;
            set;
        }
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReportStartDateTime
        {
            get;
            set;
        }
    
        public virtual int ReportDurationSeconds
        {
            get;
            set;
        }
    
        public virtual int TaskProducedG1
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReportEndDateTime
        {
            get;
            set;
        }
    
        public virtual int TaskReportTargetPoint
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Task Task
        {
            get { return _task; }
            set
            {
                if (!ReferenceEquals(_task, value))
                {
                    var previousValue = _task;
                    _task = value;
                    FixupTask(previousValue);
                }
            }
        }
        private Task _task;
    
        public virtual ICollection<ProcessReport> ProcessReports
        {
            get
            {
                if (_processReports == null)
                {
                    var newCollection = new FixupCollection<ProcessReport>();
                    newCollection.CollectionChanged += FixupProcessReports;
                    _processReports = newCollection;
                }
                return _processReports;
            }
            set
            {
                if (!ReferenceEquals(_processReports, value))
                {
                    var previousValue = _processReports as FixupCollection<ProcessReport>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProcessReports;
                    }
                    _processReports = value;
                    var newValue = value as FixupCollection<ProcessReport>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProcessReports;
                    }
                }
            }
        }
        private ICollection<ProcessReport> _processReports;

        #endregion

        #region Association Fixup
    
        private void FixupTask(Task previousValue)
        {
            if (previousValue != null && previousValue.TaskReports.Contains(this))
            {
                previousValue.TaskReports.Remove(this);
            }
    
            if (Task != null)
            {
                if (!Task.TaskReports.Contains(this))
                {
                    Task.TaskReports.Add(this);
                }
            }
        }
    
        private void FixupProcessReports(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProcessReport item in e.NewItems)
                {
                    item.TaskReport = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProcessReport item in e.OldItems)
                {
                    if (ReferenceEquals(item.TaskReport, this))
                    {
                        item.TaskReport = null;
                    }
                }
            }
        }

        #endregion

    }
}
