//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class WorkBreak
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int StartSeconds
        {
            get { return _startSeconds; }
            set { _startSeconds = value; }
        }
        private int _startSeconds = 0;
    
        public virtual int EndSeconds
        {
            get { return _endSeconds; }
            set { _endSeconds = value; }
        }
        private int _endSeconds = 0;

        #endregion

        #region Navigation Properties
    
        public virtual WorkShift WorkShift
        {
            get { return _workShift; }
            set
            {
                if (!ReferenceEquals(_workShift, value))
                {
                    var previousValue = _workShift;
                    _workShift = value;
                    FixupWorkShift(previousValue);
                }
            }
        }
        private WorkShift _workShift;

        #endregion

        #region Association Fixup
    
        private void FixupWorkShift(WorkShift previousValue)
        {
            if (previousValue != null && previousValue.WorkBreaks.Contains(this))
            {
                previousValue.WorkBreaks.Remove(this);
            }
    
            if (WorkShift != null)
            {
                if (!WorkShift.WorkBreaks.Contains(this))
                {
                    WorkShift.WorkBreaks.Add(this);
                }
            }
        }

        #endregion

    }
}
