//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class Activity
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual byte Status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte _status = 1;
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ActivityGroup ActivityGroup
        {
            get { return _activityGroup; }
            set
            {
                if (!ReferenceEquals(_activityGroup, value))
                {
                    var previousValue = _activityGroup;
                    _activityGroup = value;
                    FixupActivityGroup(previousValue);
                }
            }
        }
        private ActivityGroup _activityGroup;
    
        public virtual ICollection<GeneralActivitySkill> OperatorActivities
        {
            get
            {
                if (_operatorActivities == null)
                {
                    var newCollection = new FixupCollection<GeneralActivitySkill>();
                    newCollection.CollectionChanged += FixupOperatorActivities;
                    _operatorActivities = newCollection;
                }
                return _operatorActivities;
            }
            set
            {
                if (!ReferenceEquals(_operatorActivities, value))
                {
                    var previousValue = _operatorActivities as FixupCollection<GeneralActivitySkill>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupOperatorActivities;
                    }
                    _operatorActivities = value;
                    var newValue = value as FixupCollection<GeneralActivitySkill>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupOperatorActivities;
                    }
                }
            }
        }
        private ICollection<GeneralActivitySkill> _operatorActivities;
    
        public virtual ICollection<Cost> Costs
        {
            get
            {
                if (_costs == null)
                {
                    var newCollection = new FixupCollection<Cost>();
                    newCollection.CollectionChanged += FixupCosts;
                    _costs = newCollection;
                }
                return _costs;
            }
            set
            {
                if (!ReferenceEquals(_costs, value))
                {
                    var previousValue = _costs as FixupCollection<Cost>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCosts;
                    }
                    _costs = value;
                    var newValue = value as FixupCollection<Cost>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCosts;
                    }
                }
            }
        }
        private ICollection<Cost> _costs;
    
        public virtual ICollection<StateStationActivity> StateStationActivities
        {
            get
            {
                if (_stateStationActivities == null)
                {
                    var newCollection = new FixupCollection<StateStationActivity>();
                    newCollection.CollectionChanged += FixupStateStationActivities;
                    _stateStationActivities = newCollection;
                }
                return _stateStationActivities;
            }
            set
            {
                if (!ReferenceEquals(_stateStationActivities, value))
                {
                    var previousValue = _stateStationActivities as FixupCollection<StateStationActivity>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStateStationActivities;
                    }
                    _stateStationActivities = value;
                    var newValue = value as FixupCollection<StateStationActivity>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStateStationActivities;
                    }
                }
            }
        }
        private ICollection<StateStationActivity> _stateStationActivities;

        #endregion

        #region Association Fixup
    
        private void FixupActivityGroup(ActivityGroup previousValue)
        {
            if (previousValue != null && previousValue.Activities.Contains(this))
            {
                previousValue.Activities.Remove(this);
            }
    
            if (ActivityGroup != null)
            {
                if (!ActivityGroup.Activities.Contains(this))
                {
                    ActivityGroup.Activities.Add(this);
                }
            }
        }
    
        private void FixupOperatorActivities(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GeneralActivitySkill item in e.NewItems)
                {
                    item.Activity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GeneralActivitySkill item in e.OldItems)
                {
                    if (ReferenceEquals(item.Activity, this))
                    {
                        item.Activity = null;
                    }
                }
            }
        }
    
        private void FixupCosts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Cost item in e.NewItems)
                {
                    item.Activity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Cost item in e.OldItems)
                {
                    if (ReferenceEquals(item.Activity, this))
                    {
                        item.Activity = null;
                    }
                }
            }
        }
    
        private void FixupStateStationActivities(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (StateStationActivity item in e.NewItems)
                {
                    item.Activity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (StateStationActivity item in e.OldItems)
                {
                    if (ReferenceEquals(item.Activity, this))
                    {
                        item.Activity = null;
                    }
                }
            }
        }

        #endregion

    }
}
