//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class ActivitySkill
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual byte IluoNr
        {
            get { return _iluoNr; }
            set { _iluoNr = value; }
        }
        private byte _iluoNr = 0;
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Operator Operator
        {
            get { return _operator; }
            set
            {
                if (!ReferenceEquals(_operator, value))
                {
                    var previousValue = _operator;
                    _operator = value;
                    FixupOperator(previousValue);
                }
            }
        }
        private Operator _operator;
    
        public virtual Activity Activity
        {
            get { return _activity; }
            set
            {
                if (!ReferenceEquals(_activity, value))
                {
                    var previousValue = _activity;
                    _activity = value;
                    FixupActivity(previousValue);
                }
            }
        }
        private Activity _activity;
    
        public virtual ICollection<ProductActivitySkill> ProductActivitySkills
        {
            get
            {
                if (_productActivitySkills == null)
                {
                    var newCollection = new FixupCollection<ProductActivitySkill>();
                    newCollection.CollectionChanged += FixupProductActivitySkills;
                    _productActivitySkills = newCollection;
                }
                return _productActivitySkills;
            }
            set
            {
                if (!ReferenceEquals(_productActivitySkills, value))
                {
                    var previousValue = _productActivitySkills as FixupCollection<ProductActivitySkill>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductActivitySkills;
                    }
                    _productActivitySkills = value;
                    var newValue = value as FixupCollection<ProductActivitySkill>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductActivitySkills;
                    }
                }
            }
        }
        private ICollection<ProductActivitySkill> _productActivitySkills;

        #endregion

        #region Association Fixup
    
        private void FixupOperator(Operator previousValue)
        {
            if (previousValue != null && previousValue.ActivitySkills.Contains(this))
            {
                previousValue.ActivitySkills.Remove(this);
            }
    
            if (Operator != null)
            {
                if (!Operator.ActivitySkills.Contains(this))
                {
                    Operator.ActivitySkills.Add(this);
                }
            }
        }
    
        private void FixupActivity(Activity previousValue)
        {
            if (previousValue != null && previousValue.ActivitySkills.Contains(this))
            {
                previousValue.ActivitySkills.Remove(this);
            }
    
            if (Activity != null)
            {
                if (!Activity.ActivitySkills.Contains(this))
                {
                    Activity.ActivitySkills.Add(this);
                }
            }
        }
    
        private void FixupProductActivitySkills(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductActivitySkill item in e.NewItems)
                {
                    item.ActivitySkill = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductActivitySkill item in e.OldItems)
                {
                    if (ReferenceEquals(item.ActivitySkill, this))
                    {
                        item.ActivitySkill = null;
                    }
                }
            }
        }

        #endregion

    }
}
