//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class Defection
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual byte Status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte _status = 1;
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<ProductDefection> ProductDefections
        {
            get
            {
                if (_productDefections == null)
                {
                    var newCollection = new FixupCollection<ProductDefection>();
                    newCollection.CollectionChanged += FixupProductDefections;
                    _productDefections = newCollection;
                }
                return _productDefections;
            }
            set
            {
                if (!ReferenceEquals(_productDefections, value))
                {
                    var previousValue = _productDefections as FixupCollection<ProductDefection>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProductDefections;
                    }
                    _productDefections = value;
                    var newValue = value as FixupCollection<ProductDefection>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProductDefections;
                    }
                }
            }
        }
        private ICollection<ProductDefection> _productDefections;

        #endregion

        #region Association Fixup
    
        private void FixupProductDefections(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProductDefection item in e.NewItems)
                {
                    item.Defection = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProductDefection item in e.OldItems)
                {
                    if (ReferenceEquals(item.Defection, this))
                    {
                        item.Defection = null;
                    }
                }
            }
        }

        #endregion

    }
}
