//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class MaintenanceReport
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual System.DateTime MaintenanceDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PerformedDate
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual byte Status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte _status = 0;
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual MachinePartMaintenance MachinePartMaintenance
        {
            get { return _machinePartMaintenance; }
            set
            {
                if (!ReferenceEquals(_machinePartMaintenance, value))
                {
                    var previousValue = _machinePartMaintenance;
                    _machinePartMaintenance = value;
                    FixupMachinePartMaintenance(previousValue);
                }
            }
        }
        private MachinePartMaintenance _machinePartMaintenance;

        #endregion

        #region Association Fixup
    
        private void FixupMachinePartMaintenance(MachinePartMaintenance previousValue)
        {
            if (previousValue != null && previousValue.MaintenanceReports.Contains(this))
            {
                previousValue.MaintenanceReports.Remove(this);
            }
    
            if (MachinePartMaintenance != null)
            {
                if (!MachinePartMaintenance.MaintenanceReports.Contains(this))
                {
                    MachinePartMaintenance.MaintenanceReports.Add(this);
                }
            }
        }

        #endregion

    }
}
