//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class OperatorActivity
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual byte IluoNr
        {
            get { return _iluoNr; }
            set { _iluoNr = value; }
        }
        private byte _iluoNr = 0;
    
        private byte Status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte _status = 1;

        #endregion

        #region Navigation Properties
    
        public virtual Operator Operator
        {
            get { return _operator; }
            set
            {
                if (!ReferenceEquals(_operator, value))
                {
                    var previousValue = _operator;
                    _operator = value;
                    FixupOperator(previousValue);
                }
            }
        }
        private Operator _operator;
    
        public virtual SpecialSkill SpecialSkill
        {
            get { return _specialSkill; }
            set
            {
                if (!ReferenceEquals(_specialSkill, value))
                {
                    var previousValue = _specialSkill;
                    _specialSkill = value;
                    FixupSpecialSkill(previousValue);
                }
            }
        }
        private SpecialSkill _specialSkill;
    
        public virtual Activity Activity
        {
            get { return _activity; }
            set
            {
                if (!ReferenceEquals(_activity, value))
                {
                    var previousValue = _activity;
                    _activity = value;
                    FixupActivity(previousValue);
                }
            }
        }
        private Activity _activity;

        #endregion

        #region Association Fixup
    
        private void FixupOperator(Operator previousValue)
        {
            if (previousValue != null && previousValue.OperatorActivities.Contains(this))
            {
                previousValue.OperatorActivities.Remove(this);
            }
    
            if (Operator != null)
            {
                if (!Operator.OperatorActivities.Contains(this))
                {
                    Operator.OperatorActivities.Add(this);
                }
            }
        }
    
        private void FixupSpecialSkill(SpecialSkill previousValue)
        {
            if (previousValue != null && previousValue.OperatorActivities.Contains(this))
            {
                previousValue.OperatorActivities.Remove(this);
            }
    
            if (SpecialSkill != null)
            {
                if (!SpecialSkill.OperatorActivities.Contains(this))
                {
                    SpecialSkill.OperatorActivities.Add(this);
                }
            }
        }
    
        private void FixupActivity(Activity previousValue)
        {
            if (previousValue != null && previousValue.OperatorActivities.Contains(this))
            {
                previousValue.OperatorActivities.Remove(this);
            }
    
            if (Activity != null)
            {
                if (!Activity.OperatorActivities.Contains(this))
                {
                    Activity.OperatorActivities.Add(this);
                }
            }
        }

        #endregion

    }
}
