//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class OperatorProcessReport
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int OperatorProducedG1
        {
            get { return _operatorProducedG1; }
            set { _operatorProducedG1 = value; }
        }
        private int _operatorProducedG1 = 0;
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Operator Operator
        {
            get { return _operator; }
            set
            {
                if (!ReferenceEquals(_operator, value))
                {
                    var previousValue = _operator;
                    _operator = value;
                    FixupOperator(previousValue);
                }
            }
        }
        private Operator _operator;
    
        public virtual ProcessReport ProcessReport
        {
            get { return _processReport; }
            set
            {
                if (!ReferenceEquals(_processReport, value))
                {
                    var previousValue = _processReport;
                    _processReport = value;
                    FixupProcessReport(previousValue);
                }
            }
        }
        private ProcessReport _processReport;

        #endregion

        #region Association Fixup
    
        private void FixupOperator(Operator previousValue)
        {
            if (previousValue != null && previousValue.OperatorProcessReports.Contains(this))
            {
                previousValue.OperatorProcessReports.Remove(this);
            }
    
            if (Operator != null)
            {
                if (!Operator.OperatorProcessReports.Contains(this))
                {
                    Operator.OperatorProcessReports.Add(this);
                }
            }
        }
    
        private void FixupProcessReport(ProcessReport previousValue)
        {
            if (previousValue != null && previousValue.OperatorProcessReports.Contains(this))
            {
                previousValue.OperatorProcessReports.Remove(this);
            }
    
            if (ProcessReport != null)
            {
                if (!ProcessReport.OperatorProcessReports.Contains(this))
                {
                    ProcessReport.OperatorProcessReports.Add(this);
                }
            }
        }

        #endregion

    }
}
