//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class ProcessOperator
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        private byte RoleNr
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Process Process
        {
            get { return _process; }
            set
            {
                if (!ReferenceEquals(_process, value))
                {
                    var previousValue = _process;
                    _process = value;
                    FixupProcess(previousValue);
                }
            }
        }
        private Process _process;
    
        public virtual Operator Operator
        {
            get { return _operator; }
            set
            {
                if (!ReferenceEquals(_operator, value))
                {
                    var previousValue = _operator;
                    _operator = value;
                    FixupOperator(previousValue);
                }
            }
        }
        private Operator _operator;
    
        public virtual ICollection<ProcessOperatorReport> ProcessOperatorReports
        {
            get
            {
                if (_processOperatorReports == null)
                {
                    var newCollection = new FixupCollection<ProcessOperatorReport>();
                    newCollection.CollectionChanged += FixupProcessOperatorReports;
                    _processOperatorReports = newCollection;
                }
                return _processOperatorReports;
            }
            set
            {
                if (!ReferenceEquals(_processOperatorReports, value))
                {
                    var previousValue = _processOperatorReports as FixupCollection<ProcessOperatorReport>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProcessOperatorReports;
                    }
                    _processOperatorReports = value;
                    var newValue = value as FixupCollection<ProcessOperatorReport>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProcessOperatorReports;
                    }
                }
            }
        }
        private ICollection<ProcessOperatorReport> _processOperatorReports;

        #endregion

        #region Association Fixup
    
        private void FixupProcess(Process previousValue)
        {
            if (previousValue != null && previousValue.ProcessOperators.Contains(this))
            {
                previousValue.ProcessOperators.Remove(this);
            }
    
            if (Process != null)
            {
                if (!Process.ProcessOperators.Contains(this))
                {
                    Process.ProcessOperators.Add(this);
                }
            }
        }
    
        private void FixupOperator(Operator previousValue)
        {
            if (previousValue != null && previousValue.ProcessOperators.Contains(this))
            {
                previousValue.ProcessOperators.Remove(this);
            }
    
            if (Operator != null)
            {
                if (!Operator.ProcessOperators.Contains(this))
                {
                    Operator.ProcessOperators.Add(this);
                }
            }
        }
    
        private void FixupProcessOperatorReports(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProcessOperatorReport item in e.NewItems)
                {
                    item.ProcessOperator = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProcessOperatorReport item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProcessOperator, this))
                    {
                        item.ProcessOperator = null;
                    }
                }
            }
        }

        #endregion

    }
}
