//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class StateStationActivity
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual float CycleTime
        {
            get;
            set;
        }
    
        public virtual float ManHour
        {
            get;
            set;
        }
    
        public virtual bool IsMany
        {
            get { return _isMany; }
            set { _isMany = value; }
        }
        private bool _isMany = true;
    
        public virtual bool IsInJob
        {
            get { return _isInJob; }
            set { _isInJob = value; }
        }
        private bool _isInJob = true;
    
        public virtual bool IsPrimaryOutput
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual StateStation StateStation
        {
            get { return _stateStation; }
            set
            {
                if (!ReferenceEquals(_stateStation, value))
                {
                    var previousValue = _stateStation;
                    _stateStation = value;
                    FixupStateStation(previousValue);
                }
            }
        }
        private StateStation _stateStation;
    
        public virtual ICollection<StateStationActivityMachine> StateStationActivityMachines
        {
            get
            {
                if (_stateStationActivityMachines == null)
                {
                    var newCollection = new FixupCollection<StateStationActivityMachine>();
                    newCollection.CollectionChanged += FixupStateStationActivityMachines;
                    _stateStationActivityMachines = newCollection;
                }
                return _stateStationActivityMachines;
            }
            set
            {
                if (!ReferenceEquals(_stateStationActivityMachines, value))
                {
                    var previousValue = _stateStationActivityMachines as FixupCollection<StateStationActivityMachine>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStateStationActivityMachines;
                    }
                    _stateStationActivityMachines = value;
                    var newValue = value as FixupCollection<StateStationActivityMachine>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStateStationActivityMachines;
                    }
                }
            }
        }
        private ICollection<StateStationActivityMachine> _stateStationActivityMachines;
    
        public virtual Activity Activity
        {
            get { return _activity; }
            set
            {
                if (!ReferenceEquals(_activity, value))
                {
                    var previousValue = _activity;
                    _activity = value;
                    FixupActivity(previousValue);
                }
            }
        }
        private Activity _activity;
    
        public virtual ICollection<Process> Processes
        {
            get
            {
                if (_processes == null)
                {
                    var newCollection = new FixupCollection<Process>();
                    newCollection.CollectionChanged += FixupProcesses;
                    _processes = newCollection;
                }
                return _processes;
            }
            set
            {
                if (!ReferenceEquals(_processes, value))
                {
                    var previousValue = _processes as FixupCollection<Process>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProcesses;
                    }
                    _processes = value;
                    var newValue = value as FixupCollection<Process>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProcesses;
                    }
                }
            }
        }
        private ICollection<Process> _processes;
    
        public virtual ICollection<ExternalConnector> OutExternalConnectors
        {
            get
            {
                if (_outExternalConnectors == null)
                {
                    var newCollection = new FixupCollection<ExternalConnector>();
                    newCollection.CollectionChanged += FixupOutExternalConnectors;
                    _outExternalConnectors = newCollection;
                }
                return _outExternalConnectors;
            }
            set
            {
                if (!ReferenceEquals(_outExternalConnectors, value))
                {
                    var previousValue = _outExternalConnectors as FixupCollection<ExternalConnector>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupOutExternalConnectors;
                    }
                    _outExternalConnectors = value;
                    var newValue = value as FixupCollection<ExternalConnector>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupOutExternalConnectors;
                    }
                }
            }
        }
        private ICollection<ExternalConnector> _outExternalConnectors;
    
        public virtual ICollection<ExternalConnector> InExternalConnectors
        {
            get
            {
                if (_inExternalConnectors == null)
                {
                    var newCollection = new FixupCollection<ExternalConnector>();
                    newCollection.CollectionChanged += FixupInExternalConnectors;
                    _inExternalConnectors = newCollection;
                }
                return _inExternalConnectors;
            }
            set
            {
                if (!ReferenceEquals(_inExternalConnectors, value))
                {
                    var previousValue = _inExternalConnectors as FixupCollection<ExternalConnector>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupInExternalConnectors;
                    }
                    _inExternalConnectors = value;
                    var newValue = value as FixupCollection<ExternalConnector>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupInExternalConnectors;
                    }
                }
            }
        }
        private ICollection<ExternalConnector> _inExternalConnectors;

        #endregion

        #region Association Fixup
    
        private void FixupStateStation(StateStation previousValue)
        {
            if (previousValue != null && previousValue.StateStationActivities.Contains(this))
            {
                previousValue.StateStationActivities.Remove(this);
            }
    
            if (StateStation != null)
            {
                if (!StateStation.StateStationActivities.Contains(this))
                {
                    StateStation.StateStationActivities.Add(this);
                }
            }
        }
    
        private void FixupActivity(Activity previousValue)
        {
            if (previousValue != null && previousValue.StateStationActivities.Contains(this))
            {
                previousValue.StateStationActivities.Remove(this);
            }
    
            if (Activity != null)
            {
                if (!Activity.StateStationActivities.Contains(this))
                {
                    Activity.StateStationActivities.Add(this);
                }
            }
        }
    
        private void FixupStateStationActivityMachines(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (StateStationActivityMachine item in e.NewItems)
                {
                    item.StateStationActivity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (StateStationActivityMachine item in e.OldItems)
                {
                    if (ReferenceEquals(item.StateStationActivity, this))
                    {
                        item.StateStationActivity = null;
                    }
                }
            }
        }
    
        private void FixupProcesses(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Process item in e.NewItems)
                {
                    item.StateStationActivity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Process item in e.OldItems)
                {
                    if (ReferenceEquals(item.StateStationActivity, this))
                    {
                        item.StateStationActivity = null;
                    }
                }
            }
        }
    
        private void FixupOutExternalConnectors(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ExternalConnector item in e.NewItems)
                {
                    item.StartSSA = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ExternalConnector item in e.OldItems)
                {
                    if (ReferenceEquals(item.StartSSA, this))
                    {
                        item.StartSSA = null;
                    }
                }
            }
        }
    
        private void FixupInExternalConnectors(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ExternalConnector item in e.NewItems)
                {
                    item.EndSSA = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ExternalConnector item in e.OldItems)
                {
                    if (ReferenceEquals(item.EndSSA, this))
                    {
                        item.EndSSA = null;
                    }
                }
            }
        }

        #endregion

    }
}
