//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class Test : NonProductiveTask
    {
        #region Navigation Properties
    
        public virtual Station Station
        {
            get { return _station; }
            set
            {
                if (!ReferenceEquals(_station, value))
                {
                    var previousValue = _station;
                    _station = value;
                    FixupStation(previousValue);
                }
            }
        }
        private Station _station;

        #endregion

        #region Association Fixup
    
        private void FixupStation(Station previousValue)
        {
            if (previousValue != null && previousValue.Tests.Contains(this))
            {
                previousValue.Tests.Remove(this);
            }
    
            if (Station != null)
            {
                if (!Station.Tests.Contains(this))
                {
                    Station.Tests.Add(this);
                }
            }
        }

        #endregion

    }
}
