//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class UniqueActivitySkill
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual byte IluoNr
        {
            get { return _iluoNr; }
            set { _iluoNr = value; }
        }
        private byte _iluoNr = 0;
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Operator Operator
        {
            get { return _operator; }
            set
            {
                if (!ReferenceEquals(_operator, value))
                {
                    var previousValue = _operator;
                    _operator = value;
                    FixupOperator(previousValue);
                }
            }
        }
        private Operator _operator;
    
        public virtual StateStationActivity StateStationActivity
        {
            get { return _stateStationActivity; }
            set
            {
                if (!ReferenceEquals(_stateStationActivity, value))
                {
                    var previousValue = _stateStationActivity;
                    _stateStationActivity = value;
                    FixupStateStationActivity(previousValue);
                }
            }
        }
        private StateStationActivity _stateStationActivity;

        #endregion

        #region Association Fixup
    
        private void FixupOperator(Operator previousValue)
        {
            if (previousValue != null && previousValue.UniqueActivitySkills.Contains(this))
            {
                previousValue.UniqueActivitySkills.Remove(this);
            }
    
            if (Operator != null)
            {
                if (!Operator.UniqueActivitySkills.Contains(this))
                {
                    Operator.UniqueActivitySkills.Add(this);
                }
            }
        }
    
        private void FixupStateStationActivity(StateStationActivity previousValue)
        {
            if (previousValue != null && previousValue.UniqueActivitySkills.Contains(this))
            {
                previousValue.UniqueActivitySkills.Remove(this);
            }
    
            if (StateStationActivity != null)
            {
                if (!StateStationActivity.UniqueActivitySkills.Contains(this))
                {
                    StateStationActivity.UniqueActivitySkills.Add(this);
                }
            }
        }

        #endregion

    }
}
