//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class UnitGroup
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual byte Status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte _status = 1;
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<UnitSet> UnitSets
        {
            get
            {
                if (_unitSets == null)
                {
                    var newCollection = new FixupCollection<UnitSet>();
                    newCollection.CollectionChanged += FixupUnitSets;
                    _unitSets = newCollection;
                }
                return _unitSets;
            }
            set
            {
                if (!ReferenceEquals(_unitSets, value))
                {
                    var previousValue = _unitSets as FixupCollection<UnitSet>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUnitSets;
                    }
                    _unitSets = value;
                    var newValue = value as FixupCollection<UnitSet>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUnitSets;
                    }
                }
            }
        }
        private ICollection<UnitSet> _unitSets;
    
        public virtual ICollection<RawMaterialUnitGroup> RawMaterialUnitGroups
        {
            get
            {
                if (_rawMaterialUnitGroups == null)
                {
                    var newCollection = new FixupCollection<RawMaterialUnitGroup>();
                    newCollection.CollectionChanged += FixupRawMaterialUnitGroups;
                    _rawMaterialUnitGroups = newCollection;
                }
                return _rawMaterialUnitGroups;
            }
            set
            {
                if (!ReferenceEquals(_rawMaterialUnitGroups, value))
                {
                    var previousValue = _rawMaterialUnitGroups as FixupCollection<RawMaterialUnitGroup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRawMaterialUnitGroups;
                    }
                    _rawMaterialUnitGroups = value;
                    var newValue = value as FixupCollection<RawMaterialUnitGroup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRawMaterialUnitGroups;
                    }
                }
            }
        }
        private ICollection<RawMaterialUnitGroup> _rawMaterialUnitGroups;

        #endregion

        #region Association Fixup
    
        private void FixupUnitSets(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UnitSet item in e.NewItems)
                {
                    item.UnitGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UnitSet item in e.OldItems)
                {
                    if (ReferenceEquals(item.UnitGroup, this))
                    {
                        item.UnitGroup = null;
                    }
                }
            }
        }
    
        private void FixupRawMaterialUnitGroups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (RawMaterialUnitGroup item in e.NewItems)
                {
                    item.UnitGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RawMaterialUnitGroup item in e.OldItems)
                {
                    if (ReferenceEquals(item.UnitGroup, this))
                    {
                        item.UnitGroup = null;
                    }
                }
            }
        }

        #endregion

    }
}
