//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class UnitSet
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual byte Status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte _status = 1;
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<UnitConversion> MajorUnits
        {
            get
            {
                if (_majorUnits == null)
                {
                    var newCollection = new FixupCollection<UnitConversion>();
                    newCollection.CollectionChanged += FixupMajorUnits;
                    _majorUnits = newCollection;
                }
                return _majorUnits;
            }
            set
            {
                if (!ReferenceEquals(_majorUnits, value))
                {
                    var previousValue = _majorUnits as FixupCollection<UnitConversion>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMajorUnits;
                    }
                    _majorUnits = value;
                    var newValue = value as FixupCollection<UnitConversion>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMajorUnits;
                    }
                }
            }
        }
        private ICollection<UnitConversion> _majorUnits;
    
        public virtual ICollection<UnitConversion> MinorUnits
        {
            get
            {
                if (_minorUnits == null)
                {
                    var newCollection = new FixupCollection<UnitConversion>();
                    newCollection.CollectionChanged += FixupMinorUnits;
                    _minorUnits = newCollection;
                }
                return _minorUnits;
            }
            set
            {
                if (!ReferenceEquals(_minorUnits, value))
                {
                    var previousValue = _minorUnits as FixupCollection<UnitConversion>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMinorUnits;
                    }
                    _minorUnits = value;
                    var newValue = value as FixupCollection<UnitConversion>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMinorUnits;
                    }
                }
            }
        }
        private ICollection<UnitConversion> _minorUnits;
    
        public virtual UnitGroup UnitGroup
        {
            get { return _unitGroup; }
            set
            {
                if (!ReferenceEquals(_unitGroup, value))
                {
                    var previousValue = _unitGroup;
                    _unitGroup = value;
                    FixupUnitGroup(previousValue);
                }
            }
        }
        private UnitGroup _unitGroup;
    
        public virtual ICollection<BOM> BOMs
        {
            get
            {
                if (_bOMs == null)
                {
                    var newCollection = new FixupCollection<BOM>();
                    newCollection.CollectionChanged += FixupBOMs;
                    _bOMs = newCollection;
                }
                return _bOMs;
            }
            set
            {
                if (!ReferenceEquals(_bOMs, value))
                {
                    var previousValue = _bOMs as FixupCollection<BOM>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBOMs;
                    }
                    _bOMs = value;
                    var newValue = value as FixupCollection<BOM>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBOMs;
                    }
                }
            }
        }
        private ICollection<BOM> _bOMs;

        #endregion

        #region Association Fixup
    
        private void FixupUnitGroup(UnitGroup previousValue)
        {
            if (previousValue != null && previousValue.UnitSets.Contains(this))
            {
                previousValue.UnitSets.Remove(this);
            }
    
            if (UnitGroup != null)
            {
                if (!UnitGroup.UnitSets.Contains(this))
                {
                    UnitGroup.UnitSets.Add(this);
                }
            }
        }
    
        private void FixupMajorUnits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UnitConversion item in e.NewItems)
                {
                    item.MajorUnit = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UnitConversion item in e.OldItems)
                {
                    if (ReferenceEquals(item.MajorUnit, this))
                    {
                        item.MajorUnit = null;
                    }
                }
            }
        }
    
        private void FixupMinorUnits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UnitConversion item in e.NewItems)
                {
                    item.MinorUnit = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UnitConversion item in e.OldItems)
                {
                    if (ReferenceEquals(item.MinorUnit, this))
                    {
                        item.MinorUnit = null;
                    }
                }
            }
        }
    
        private void FixupBOMs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BOM item in e.NewItems)
                {
                    item.UnitSet = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BOM item in e.OldItems)
                {
                    if (ReferenceEquals(item.UnitSet, this))
                    {
                        item.UnitSet = null;
                    }
                }
            }
        }

        #endregion

    }
}
