//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class User_AccessRule
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<byte> Type
        {
            get;
            set;
        }
    
        public virtual int ModifiedBy
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifiedDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual AccessRule AccessRule
        {
            get { return _accessRule; }
            set
            {
                if (!ReferenceEquals(_accessRule, value))
                {
                    var previousValue = _accessRule;
                    _accessRule = value;
                    FixupAccessRule(previousValue);
                }
            }
        }
        private AccessRule _accessRule;

        #endregion

        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.User_AccessRules.Contains(this))
            {
                previousValue.User_AccessRules.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.User_AccessRules.Contains(this))
                {
                    User.User_AccessRules.Add(this);
                }
            }
        }
    
        private void FixupAccessRule(AccessRule previousValue)
        {
            if (previousValue != null && previousValue.User_AccessRules.Contains(this))
            {
                previousValue.User_AccessRules.Remove(this);
            }
    
            if (AccessRule != null)
            {
                if (!AccessRule.User_AccessRules.Contains(this))
                {
                    AccessRule.User_AccessRules.Add(this);
                }
            }
        }

        #endregion

    }
}
