//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soheil.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soheil.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی کامل.
        /// </summary>
        public static string AccessType_Full {
            get {
                return ResourceManager.GetString("AccessType_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string AccessType_Insert {
            get {
                return ResourceManager.GetString("AccessType_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون دسترسی.
        /// </summary>
        public static string AccessType_None {
            get {
                return ResourceManager.GetString("AccessType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ.
        /// </summary>
        public static string AccessType_Print {
            get {
                return ResourceManager.GetString("AccessType_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string AccessType_Update {
            get {
                return ResourceManager.GetString("AccessType_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string AccessType_View {
            get {
                return ResourceManager.GetString("AccessType_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح 1.
        /// </summary>
        public static string CauseLevel_Level1 {
            get {
                return ResourceManager.GetString("CauseLevel_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح 2.
        /// </summary>
        public static string CauseLevel_Level2 {
            get {
                return ResourceManager.GetString("CauseLevel_Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح 3.
        /// </summary>
        public static string CauseLevel_Level3 {
            get {
                return ResourceManager.GetString("CauseLevel_Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CauseLevel_None {
            get {
                return ResourceManager.GetString("CauseLevel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت.
        /// </summary>
        public static string CostSourceType_Activities {
            get {
                return ResourceManager.GetString("CostSourceType_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماشین.
        /// </summary>
        public static string CostSourceType_Machines {
            get {
                return ResourceManager.GetString("CostSourceType_Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتور.
        /// </summary>
        public static string CostSourceType_Operators {
            get {
                return ResourceManager.GetString("CostSourceType_Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متفرقه.
        /// </summary>
        public static string CostSourceType_Other {
            get {
                return ResourceManager.GetString("CostSourceType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایستگاه.
        /// </summary>
        public static string CostSourceType_Stations {
            get {
                return ResourceManager.GetString("CostSourceType_Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه کل.
        /// </summary>
        public static string CostType_All {
            get {
                return ResourceManager.GetString("CostType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدی.
        /// </summary>
        public static string CostType_Cash {
            get {
                return ResourceManager.GetString("CostType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی.
        /// </summary>
        public static string CostType_Stock {
            get {
                return ResourceManager.GetString("CostType_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزانه.
        /// </summary>
        public static string DateTimeIntervals_Daily {
            get {
                return ResourceManager.GetString("DateTimeIntervals_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعتی.
        /// </summary>
        public static string DateTimeIntervals_Hourly {
            get {
                return ResourceManager.GetString("DateTimeIntervals_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماهانه.
        /// </summary>
        public static string DateTimeIntervals_Monthly {
            get {
                return ResourceManager.GetString("DateTimeIntervals_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نشده.
        /// </summary>
        public static string DateTimeIntervals_None {
            get {
                return ResourceManager.GetString("DateTimeIntervals_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شیفتی.
        /// </summary>
        public static string DateTimeIntervals_Shiftly {
            get {
                return ResourceManager.GetString("DateTimeIntervals_Shiftly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتگی.
        /// </summary>
        public static string DateTimeIntervals_Weekly {
            get {
                return ResourceManager.GetString("DateTimeIntervals_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالانه.
        /// </summary>
        public static string DateTimeIntervals_Yearly {
            get {
                return ResourceManager.GetString("DateTimeIntervals_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        public static string enumDirection {
            get {
                return ResourceManager.GetString("enumDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماشین آلات.
        /// </summary>
        public static string FishboneNodeType_Machine {
            get {
                return ResourceManager.GetString("FishboneNodeType_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعمیر و نگهداری.
        /// </summary>
        public static string FishboneNodeType_Maintenance {
            get {
                return ResourceManager.GetString("FishboneNodeType_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیروی انسانی.
        /// </summary>
        public static string FishboneNodeType_Man {
            get {
                return ResourceManager.GetString("FishboneNodeType_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد.
        /// </summary>
        public static string FishboneNodeType_Material {
            get {
                return ResourceManager.GetString("FishboneNodeType_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش.
        /// </summary>
        public static string FishboneNodeType_Method {
            get {
                return ResourceManager.GetString("FishboneNodeType_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPM داخلی.
        /// </summary>
        public static string IndexType_InternalPPM {
            get {
                return ResourceManager.GetString("IndexType_InternalPPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نشده.
        /// </summary>
        public static string IndexType_None {
            get {
                return ResourceManager.GetString("IndexType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE.
        /// </summary>
        public static string IndexType_OEE {
            get {
                return ResourceManager.GetString("IndexType_OEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد اجرا.
        /// </summary>
        public static string IndexType_Performance {
            get {
                return ResourceManager.GetString("IndexType_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت باقیمانده.
        /// </summary>
        public static string IndexType_RemainingCapacity {
            get {
                return ResourceManager.GetString("IndexType_RemainingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شد.
        /// </summary>
        public static string ModificationStatus_Saved {
            get {
                return ResourceManager.GetString("ModificationStatus_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModificationStatus_Unchanged {
            get {
                return ResourceManager.GetString("ModificationStatus_Unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره نشده.
        /// </summary>
        public static string ModificationStatus_Unsaved {
            get {
                return ResourceManager.GetString("ModificationStatus_Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا این برنامه حذف شود؟.
        /// </summary>
        public static string msgDeleteTask {
            get {
                return ResourceManager.GetString("msgDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تعداد.
        /// </summary>
        public static string OEType_CountBased {
            get {
                return ResourceManager.GetString("OEType_CountBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فرض.
        /// </summary>
        public static string OEType_None {
            get {
                return ResourceManager.GetString("OEType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براساس زمان.
        /// </summary>
        public static string OEType_TimeBased {
            get {
                return ResourceManager.GetString("OEType_TimeBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقادیر مستقل برای هر فعالیت.
        /// </summary>
        public static string PPE_DeferToActivites {
            get {
                return ResourceManager.GetString("PPE_DeferToActivites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان یا مقدار هدف.
        /// </summary>
        public static string PPE_DurationOrTP {
            get {
                return ResourceManager.GetString("PPE_DurationOrTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولین زمان خالی.
        /// </summary>
        public static string PPE_FirstEmptySpace {
            get {
                return ResourceManager.GetString("PPE_FirstEmptySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت نامعتبر.
        /// </summary>
        public static string PPE_InvalidDuration {
            get {
                return ResourceManager.GetString("PPE_InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین زمان خالی.
        /// </summary>
        public static string PPE_LastEmptySpace {
            get {
                return ResourceManager.GetString("PPE_LastEmptySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت +1.
        /// </summary>
        public static string PPE_NextHour {
            get {
                return ResourceManager.GetString("PPE_NextHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت -1.
        /// </summary>
        public static string PPE_PreviousHour {
            get {
                return ResourceManager.GetString("PPE_PreviousHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار هدف مساوی برای فعالیتها.
        /// </summary>
        public static string PPE_SameQtyForActivites {
            get {
                return ResourceManager.GetString("PPE_SameQtyForActivites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت تولید مساوی برای فعالیتها.
        /// </summary>
        public static string PPE_SameTimeForActivites {
            get {
                return ResourceManager.GetString("PPE_SameTimeForActivites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدای ساعت.
        /// </summary>
        public static string PPE_StartOfHour {
            get {
                return ResourceManager.GetString("PPE_StartOfHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع کل هدف.
        /// </summary>
        public static string PPE_SumOfTP {
            get {
                return ResourceManager.GetString("PPE_SumOfTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تولید ایستگاه.
        /// </summary>
        public static string PPE_TaskDuration {
            get {
                return ResourceManager.GetString("PPE_TaskDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار هدف ایستگاه.
        /// </summary>
        public static string PPE_TaskTP {
            get {
                return ResourceManager.GetString("PPE_TaskTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات بیشتر....
        /// </summary>
        public static string splitContentMoreInfo {
            get {
                return ResourceManager.GetString("splitContentMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string Status_Deleted {
            get {
                return ResourceManager.GetString("Status_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال.
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به اتمام رسیده.
        /// </summary>
        public static string StockStatus_Empty {
            get {
                return ResourceManager.GetString("StockStatus_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولیه.
        /// </summary>
        public static string StockStatus_Full {
            get {
                return ResourceManager.GetString("StockStatus_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصرف شده.
        /// </summary>
        public static string StockStatus_Used {
            get {
                return ResourceManager.GetString("StockStatus_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string ttBlock {
            get {
                return ResourceManager.GetString("ttBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string ttCode {
            get {
                return ResourceManager.GetString("ttCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئی از Job.
        /// </summary>
        public static string ttHasJob {
            get {
                return ResourceManager.GetString("ttHasJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو بر اساس شروع و مهلت Jobها.
        /// </summary>
        public static string ttJobListByDefinition {
            get {
                return ResourceManager.GetString("ttJobListByDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو بر اساس شروع و خاتمه Taskهای هر Job.
        /// </summary>
        public static string ttJobListByTasks {
            get {
                return ResourceManager.GetString("ttJobListByTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین شیفت این برنامه زمانی (درست به هنگام فرارسیدن برنامه بعدی) ممکن است ناقص بماند. رفتار این شیفت مطابق گزینه انتخاب شده خواهد بود. گزینه ها: Incomplete: ناقص بماند، WithLastShift: جزوی از شیفت قبل خود محسوب شود، Closed: تعطیل در نظر گرفته شود.
        /// </summary>
        public static string ttMergingStrategy {
            get {
                return ResourceManager.GetString("ttMergingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش کامل است.
        /// </summary>
        public static string ttReportCompleted {
            get {
                return ResourceManager.GetString("ttReportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد تکمیل گزارش.
        /// </summary>
        public static string ttReportFillPercent {
            get {
                return ResourceManager.GetString("ttReportFillPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخشی از Task.
        /// </summary>
        public static string ttTask {
            get {
                return ResourceManager.GetString("ttTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ی سهیل.
        /// </summary>
        public static string txtAbout {
            get {
                return ResourceManager.GetString("txtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین دسترسی.
        /// </summary>
        public static string txtAccessRules {
            get {
                return ResourceManager.GetString("txtAccessRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال در آیتم های داخلی.
        /// </summary>
        public static string txtAccessToSubItems {
            get {
                return ResourceManager.GetString("txtAccessToSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه ها.
        /// </summary>
        public static string txtActionPlans {
            get {
                return ResourceManager.GetString("txtActionPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت ها.
        /// </summary>
        public static string txtActivities {
            get {
                return ResourceManager.GetString("txtActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت.
        /// </summary>
        public static string txtActivity {
            get {
                return ResourceManager.GetString("txtActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروههای فعالیت.
        /// </summary>
        public static string txtActivityGroups {
            get {
                return ResourceManager.GetString("txtActivityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش هزینه های تمام شده.
        /// </summary>
        public static string txtActualCostReports {
            get {
                return ResourceManager.GetString("txtActualCostReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string txtBack {
            get {
                return ResourceManager.GetString("txtBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاری روز.
        /// </summary>
        public static string txtBusinessDayState {
            get {
                return ResourceManager.GetString("txtBusinessDayState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم تاثیر پست سازمانی.
        /// </summary>
        public static string txtBypassAccess {
            get {
                return ResourceManager.GetString("txtBypassAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string txtCancel {
            get {
                return ResourceManager.GetString("txtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدی.
        /// </summary>
        public static string txtCash {
            get {
                return ResourceManager.GetString("txtCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علت ها.
        /// </summary>
        public static string txtCauses {
            get {
                return ResourceManager.GetString("txtCauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد :.
        /// </summary>
        public static string txtCDate {
            get {
                return ResourceManager.GetString("txtCDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب همه.
        /// </summary>
        public static string txtCheckAll {
            get {
                return ResourceManager.GetString("txtCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string txtClose {
            get {
                return ResourceManager.GetString("txtClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد :.
        /// </summary>
        public static string txtCode {
            get {
                return ResourceManager.GetString("txtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رکورد را وارد نمایید.
        /// </summary>
        public static string txtCodeRequired {
            get {
                return ResourceManager.GetString("txtCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ :.
        /// </summary>
        public static string txtColor {
            get {
                return ResourceManager.GetString("txtColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید کلمه عبور :.
        /// </summary>
        public static string txtConfirmPassword {
            get {
                return ResourceManager.GetString("txtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترل تولید.
        /// </summary>
        public static string txtControl {
            get {
                return ResourceManager.GetString("txtControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه :.
        /// </summary>
        public static string txtCost {
            get {
                return ResourceManager.GetString("txtCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز هزینه :.
        /// </summary>
        public static string txtCostCenter {
            get {
                return ResourceManager.GetString("txtCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش هزینه ها.
        /// </summary>
        public static string txtCostReports {
            get {
                return ResourceManager.GetString("txtCostReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه ها.
        /// </summary>
        public static string txtCosts {
            get {
                return ResourceManager.GetString("txtCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع هزینه :.
        /// </summary>
        public static string txtCostSource {
            get {
                return ResourceManager.GetString("txtCostSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع هزینه :.
        /// </summary>
        public static string txtCostType {
            get {
                return ResourceManager.GetString("txtCostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه کل :.
        /// </summary>
        public static string txtCostValue {
            get {
                return ResourceManager.GetString("txtCostValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی فعلی :.
        /// </summary>
        public static string txtCurrentQuantity {
            get {
                return ResourceManager.GetString("txtCurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان سیکل.
        /// </summary>
        public static string txtCycleTime {
            get {
                return ResourceManager.GetString("txtCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان سیکل (ثانیه).
        /// </summary>
        public static string txtCycleTimeSec {
            get {
                return ResourceManager.GetString("txtCycleTimeSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string txtDate {
            get {
                return ResourceManager.GetString("txtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت.
        /// </summary>
        public static string txtDeadline {
            get {
                return ResourceManager.GetString("txtDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عیب.
        /// </summary>
        public static string txtDefection {
            get {
                return ResourceManager.GetString("txtDefection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تولید معیوب.
        /// </summary>
        public static string txtDefectionCount {
            get {
                return ResourceManager.GetString("txtDefectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عیوب.
        /// </summary>
        public static string txtDefections {
            get {
                return ResourceManager.GetString("txtDefections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تولید معیوب.
        /// </summary>
        public static string txtDefectionTime {
            get {
                return ResourceManager.GetString("txtDefectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید معیوب.
        /// </summary>
        public static string txtDefectionValue {
            get {
                return ResourceManager.GetString("txtDefectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعاریف.
        /// </summary>
        public static string txtDefinitions {
            get {
                return ResourceManager.GetString("txtDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string txtDelete {
            get {
                return ResourceManager.GetString("txtDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات :.
        /// </summary>
        public static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عیب یابی.
        /// </summary>
        public static string txtDiagnosis {
            get {
                return ResourceManager.GetString("txtDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت.
        /// </summary>
        public static string txtDuration {
            get {
                return ResourceManager.GetString("txtDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string txtEdit {
            get {
                return ResourceManager.GetString("txtEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحصیلات :.
        /// </summary>
        public static string txtEducation {
            get {
                return ResourceManager.GetString("txtEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ خاتمه.
        /// </summary>
        public static string txtEndDate {
            get {
                return ResourceManager.GetString("txtEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان خاتمه.
        /// </summary>
        public static string txtEndTime {
            get {
                return ResourceManager.GetString("txtEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف انتخاب شده ها.
        /// </summary>
        public static string txtExcludeChecked {
            get {
                return ResourceManager.GetString("txtExcludeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string txtExit {
            get {
                return ResourceManager.GetString("txtExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخوان ماهی.
        /// </summary>
        public static string txtFishboneNodes {
            get {
                return ResourceManager.GetString("txtFishboneNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPC.
        /// </summary>
        public static string txtFPC {
            get {
                return ResourceManager.GetString("txtFPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهارت کلی.
        /// </summary>
        public static string txtGenSkill {
            get {
                return ResourceManager.GetString("txtGenSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهارت های کلی.
        /// </summary>
        public static string txtGenSkills {
            get {
                return ResourceManager.GetString("txtGenSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه :.
        /// </summary>
        public static string txtGroup {
            get {
                return ResourceManager.GetString("txtGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیم ساعت.
        /// </summary>
        public static string txtHalfHour {
            get {
                return ResourceManager.GetString("txtHalfHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنما.
        /// </summary>
        public static string txtHelp {
            get {
                return ResourceManager.GetString("txtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعطیلات رسمی.
        /// </summary>
        public static string txtHolidays {
            get {
                return ResourceManager.GetString("txtHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن همه.
        /// </summary>
        public static string txtIncludeAll {
            get {
                return ResourceManager.GetString("txtIncludeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن انتخاب شده ها.
        /// </summary>
        public static string txtIncludeChecked {
            get {
                return ResourceManager.GetString("txtIncludeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان بندی :.
        /// </summary>
        public static string txtIndexInterval {
            get {
                return ResourceManager.GetString("txtIndexInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع شاخص :.
        /// </summary>
        public static string txtIndexType {
            get {
                return ResourceManager.GetString("txtIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخص ها.
        /// </summary>
        public static string txtIndices {
            get {
                return ResourceManager.GetString("txtIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال استفاده.
        /// </summary>
        public static string txtInUse {
            get {
                return ResourceManager.GetString("txtInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضایعات است.
        /// </summary>
        public static string txtIsDefection {
            get {
                return ResourceManager.GetString("txtIsDefection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی درجه 2 است.
        /// </summary>
        public static string txtIsG2 {
            get {
                return ResourceManager.GetString("txtIsG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیش از یکبار قابل استفاده است.
        /// </summary>
        public static string txtIsMany {
            get {
                return ResourceManager.GetString("txtIsMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوباره کاری.
        /// </summary>
        public static string txtIsRework {
            get {
                return ResourceManager.GetString("txtIsRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string txtLogin {
            get {
                return ResourceManager.GetString("txtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماشین آلات.
        /// </summary>
        public static string txtMachine {
            get {
                return ResourceManager.GetString("txtMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماشین ها.
        /// </summary>
        public static string txtMachines {
            get {
                return ResourceManager.GetString("txtMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعمیر و نگهداری.
        /// </summary>
        public static string txtMaintenance {
            get {
                return ResourceManager.GetString("txtMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیروی انسانی.
        /// </summary>
        public static string txtMan {
            get {
                return ResourceManager.GetString("txtMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نفرساعت.
        /// </summary>
        public static string txtManHour {
            get {
                return ResourceManager.GetString("txtManHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نفرساعتهای مجاز.
        /// </summary>
        public static string txtManHours {
            get {
                return ResourceManager.GetString("txtManHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد.
        /// </summary>
        public static string txtMaterial {
            get {
                return ResourceManager.GetString("txtMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کننده :.
        /// </summary>
        public static string txtMBy {
            get {
                return ResourceManager.GetString("txtMBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ویرایش :.
        /// </summary>
        public static string txtMDate {
            get {
                return ResourceManager.GetString("txtMDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفتار شیفت ناقص.
        /// </summary>
        public static string txtMergingStrategy {
            get {
                return ResourceManager.GetString("txtMergingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش.
        /// </summary>
        public static string txtMethod {
            get {
                return ResourceManager.GetString("txtMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        public static string txtMode {
            get {
                return ResourceManager.GetString("txtMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد ها.
        /// </summary>
        public static string txtModules {
            get {
                return ResourceManager.GetString("txtModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام :.
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام رکورد را وارد نمایید.
        /// </summary>
        public static string txtNameRequired {
            get {
                return ResourceManager.GetString("txtNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string txtNew {
            get {
                return ResourceManager.GetString("txtNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد شیفت.
        /// </summary>
        public static string txtNumberOfShifts {
            get {
                return ResourceManager.GetString("txtNumberOfShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک ساعت.
        /// </summary>
        public static string txtOneHour {
            get {
                return ResourceManager.GetString("txtOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد اپراتورها.
        /// </summary>
        public static string txtOperationReports {
            get {
                return ResourceManager.GetString("txtOperationReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتور.
        /// </summary>
        public static string txtOperator {
            get {
                return ResourceManager.GetString("txtOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتورها.
        /// </summary>
        public static string txtOperators {
            get {
                return ResourceManager.GetString("txtOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اپراتورها.
        /// </summary>
        public static string txtOperatorsCount {
            get {
                return ResourceManager.GetString("txtOperatorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختیارات.
        /// </summary>
        public static string txtOptions {
            get {
                return ResourceManager.GetString("txtOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان.
        /// </summary>
        public static string txtOrganization {
            get {
                return ResourceManager.GetString("txtOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمانهای کاری.
        /// </summary>
        public static string txtOrganizationCalendar {
            get {
                return ResourceManager.GetString("txtOrganizationCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چارت سازمانی.
        /// </summary>
        public static string txtOrgChart {
            get {
                return ResourceManager.GetString("txtOrgChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چارت های سازمانی.
        /// </summary>
        public static string txtOrgCharts {
            get {
                return ResourceManager.GetString("txtOrgCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اولیه :.
        /// </summary>
        public static string txtOriginalQty {
            get {
                return ResourceManager.GetString("txtOriginalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر.
        /// </summary>
        public static string txtOther {
            get {
                return ResourceManager.GetString("txtOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ :.
        /// </summary>
        public static string txtPaidCost {
            get {
                return ResourceManager.GetString("txtPaidCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار قطعات.
        /// </summary>
        public static string txtPartWarehouse {
            get {
                return ResourceManager.GetString("txtPartWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار های قطعات.
        /// </summary>
        public static string txtPartWarehouses {
            get {
                return ResourceManager.GetString("txtPartWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه انبار قطعات :.
        /// </summary>
        public static string txtPartWHGroup {
            get {
                return ResourceManager.GetString("txtPartWHGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور :.
        /// </summary>
        public static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملکرد.
        /// </summary>
        public static string txtPerformance {
            get {
                return ResourceManager.GetString("txtPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت بدنی :.
        /// </summary>
        public static string txtPhysicals {
            get {
                return ResourceManager.GetString("txtPhysicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست سازمانی.
        /// </summary>
        public static string txtPosition {
            get {
                return ResourceManager.GetString("txtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست های سازمانی.
        /// </summary>
        public static string txtPositions {
            get {
                return ResourceManager.GetString("txtPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ.
        /// </summary>
        public static string txtPrint {
            get {
                return ResourceManager.GetString("txtPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید سالم.
        /// </summary>
        public static string txtProducedG1 {
            get {
                return ResourceManager.GetString("txtProducedG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        public static string txtProduct {
            get {
                return ResourceManager.GetString("txtProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترل تولید.
        /// </summary>
        public static string txtProductControl {
            get {
                return ResourceManager.GetString("txtProductControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار تولید سالم.
        /// </summary>
        public static string txtProductionCount {
            get {
                return ResourceManager.GetString("txtProductionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تولید سالم.
        /// </summary>
        public static string txtProductionTime {
            get {
                return ResourceManager.GetString("txtProductionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید سالم.
        /// </summary>
        public static string txtProductionValue {
            get {
                return ResourceManager.GetString("txtProductionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه تولید.
        /// </summary>
        public static string txtProductPlan {
            get {
                return ResourceManager.GetString("txtProductPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات.
        /// </summary>
        public static string txtProducts {
            get {
                return ResourceManager.GetString("txtProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد :.
        /// </summary>
        public static string txtQty {
            get {
                return ResourceManager.GetString("txtQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد : .
        /// </summary>
        public static string txtQuantity {
            get {
                return ResourceManager.GetString("txtQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ربع ساعت.
        /// </summary>
        public static string txtQuarterHour {
            get {
                return ResourceManager.GetString("txtQuarterHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی.
        /// </summary>
        public static string txtRefresh {
            get {
                return ResourceManager.GetString("txtRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release time.
        /// </summary>
        public static string txtReleaseTime {
            get {
                return ResourceManager.GetString("txtReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشات.
        /// </summary>
        public static string txtReports {
            get {
                return ResourceManager.GetString("txtReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات1 :.
        /// </summary>
        public static string txtRes1 {
            get {
                return ResourceManager.GetString("txtRes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات2 :.
        /// </summary>
        public static string txtRes2 {
            get {
                return ResourceManager.GetString("txtRes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات3 :.
        /// </summary>
        public static string txtRes3 {
            get {
                return ResourceManager.GetString("txtRes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوباره کاری.
        /// </summary>
        public static string txtRework {
            get {
                return ResourceManager.GetString("txtRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوباره کاری ها.
        /// </summary>
        public static string txtReworks {
            get {
                return ResourceManager.GetString("txtReworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریشه ها.
        /// </summary>
        public static string txtRoots {
            get {
                return ResourceManager.GetString("txtRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قانون دسترسی.
        /// </summary>
        public static string txtRule {
            get {
                return ResourceManager.GetString("txtRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین دسترسی.
        /// </summary>
        public static string txtRules {
            get {
                return ResourceManager.GetString("txtRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string txtSave {
            get {
                return ResourceManager.GetString("txtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو :.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع هزینه :.
        /// </summary>
        public static string txtSelectedCostSource {
            get {
                return ResourceManager.GetString("txtSelectedCostSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب شده.
        /// </summary>
        public static string txtSelecteds {
            get {
                return ResourceManager.GetString("txtSelecteds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت کاری مطابق:.
        /// </summary>
        public static string txtSelectWorkProfile {
            get {
                return ResourceManager.GetString("txtSelectWorkProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string txtSettings {
            get {
                return ResourceManager.GetString("txtSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان راه اندازی.
        /// </summary>
        public static string txtSetupTimes {
            get {
                return ResourceManager.GetString("txtSetupTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ هر شیفت.
        /// </summary>
        public static string txtShiftPrototypeColor {
            get {
                return ResourceManager.GetString("txtShiftPrototypeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام هر شیفت.
        /// </summary>
        public static string txtShiftPrototypeName {
            get {
                return ResourceManager.GetString("txtShiftPrototypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مهارت.
        /// </summary>
        public static string txtSkillCenter {
            get {
                return ResourceManager.GetString("txtSkillCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مهارت اپراتورها.
        /// </summary>
        public static string txtSkillCenterForOperators {
            get {
                return ResourceManager.GetString("txtSkillCenterForOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز مهارت محصولات.
        /// </summary>
        public static string txtSkillCenterForProducts {
            get {
                return ResourceManager.GetString("txtSkillCenterForProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهیل.
        /// </summary>
        public static string txtSoheil {
            get {
                return ResourceManager.GetString("txtSoheil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهارت ویژه.
        /// </summary>
        public static string txtSpeSkill {
            get {
                return ResourceManager.GetString("txtSpeSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهارت های ویژه.
        /// </summary>
        public static string txtSpeSkills {
            get {
                return ResourceManager.GetString("txtSpeSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string txtStartDate {
            get {
                return ResourceManager.GetString("txtStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع.
        /// </summary>
        public static string txtStartPage {
            get {
                return ResourceManager.GetString("txtStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع.
        /// </summary>
        public static string txtStartTime {
            get {
                return ResourceManager.GetString("txtStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایستگاه.
        /// </summary>
        public static string txtStation {
            get {
                return ResourceManager.GetString("txtStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب ایستگاه.
        /// </summary>
        public static string txtStationIndex {
            get {
                return ResourceManager.GetString("txtStationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایستگاه ها.
        /// </summary>
        public static string txtStations {
            get {
                return ResourceManager.GetString("txtStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت :.
        /// </summary>
        public static string txtStatus {
            get {
                return ResourceManager.GetString("txtStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی.
        /// </summary>
        public static string txtStock {
            get {
                return ResourceManager.GetString("txtStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت موجودی :.
        /// </summary>
        public static string txtStockStatus {
            get {
                return ResourceManager.GetString("txtStockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار توقفات.
        /// </summary>
        public static string txtStoppageCount {
            get {
                return ResourceManager.GetString("txtStoppageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان توقفات.
        /// </summary>
        public static string txtStoppageTime {
            get {
                return ResourceManager.GetString("txtStoppageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقفات.
        /// </summary>
        public static string txtStoppageValue {
            get {
                return ResourceManager.GetString("txtStoppageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار هدف.
        /// </summary>
        public static string txtTargetCount {
            get {
                return ResourceManager.GetString("txtTargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار هدف.
        /// </summary>
        public static string txtTargetPoint {
            get {
                return ResourceManager.GetString("txtTargetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان هدف.
        /// </summary>
        public static string txtTargetTime {
            get {
                return ResourceManager.GetString("txtTargetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هدف.
        /// </summary>
        public static string txtTargetValue {
            get {
                return ResourceManager.GetString("txtTargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان.
        /// </summary>
        public static string txtTime {
            get {
                return ResourceManager.GetString("txtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امروز.
        /// </summary>
        public static string txtToday {
            get {
                return ResourceManager.GetString("txtToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فردا.
        /// </summary>
        public static string txtTomorrow {
            get {
                return ResourceManager.GetString("txtTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه کل : .
        /// </summary>
        public static string txtTotalCost {
            get {
                return ResourceManager.GetString("txtTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل :.
        /// </summary>
        public static string txtTotalQty {
            get {
                return ResourceManager.GetString("txtTotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب هیچ.
        /// </summary>
        public static string txtUncheckAll {
            get {
                return ResourceManager.GetString("txtUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه واحد :.
        /// </summary>
        public static string txtUnitCost {
            get {
                return ResourceManager.GetString("txtUnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string txtUser {
            get {
                return ResourceManager.GetString("txtUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی کاربران.
        /// </summary>
        public static string txtUserAccounts {
            get {
                return ResourceManager.GetString("txtUserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری :.
        /// </summary>
        public static string txtUsername {
            get {
                return ResourceManager.GetString("txtUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string txtUsers {
            get {
                return ResourceManager.GetString("txtUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی کاربران.
        /// </summary>
        public static string txtUsersAccess {
            get {
                return ResourceManager.GetString("txtUsersAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایام هفته.
        /// </summary>
        public static string txtWeekDays {
            get {
                return ResourceManager.GetString("txtWeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع هفته.
        /// </summary>
        public static string txtWeekStart {
            get {
                return ResourceManager.GetString("txtWeekStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه زمانی.
        /// </summary>
        public static string txtWorkProfilePlan {
            get {
                return ResourceManager.GetString("txtWorkProfilePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف ساعات کاری.
        /// </summary>
        public static string txtWorkProfiles {
            get {
                return ResourceManager.GetString("txtWorkProfiles", resourceCulture);
            }
        }
    }
}
