//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Soheil.Model
{
    public partial class CostCenter
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual byte Status
        {
            get { return _status; }
            set { _status = value; }
        }
        private byte _status = 1;
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual byte SourceType
        {
            get { return _sourceType; }
            set { _sourceType = value; }
        }
        private byte _sourceType = 1;

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Cost> Costs
        {
            get
            {
                if (_costs == null)
                {
                    var newCollection = new FixupCollection<Cost>();
                    newCollection.CollectionChanged += FixupCosts;
                    _costs = newCollection;
                }
                return _costs;
            }
            set
            {
                if (!ReferenceEquals(_costs, value))
                {
                    var previousValue = _costs as FixupCollection<Cost>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCosts;
                    }
                    _costs = value;
                    var newValue = value as FixupCollection<Cost>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCosts;
                    }
                }
            }
        }
        private ICollection<Cost> _costs;

        #endregion

        #region Association Fixup
    
        private void FixupCosts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Cost item in e.NewItems)
                {
                    item.CostCenter = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Cost item in e.OldItems)
                {
                    if (ReferenceEquals(item.CostCenter, this))
                    {
                        item.CostCenter = null;
                    }
                }
            }
        }

        #endregion

    }
}
